(defpackage :monome
  (:use :common-lisp :cffi)

  (:export
   "MONOME-EVENT-TYPE-T"
   "MONOME-ROTATE-T"
   "MONOME-T"
   "MONOME-PTR-T"
   "MONOME-EVENT-T"
   "MONOME-EVENT-PTR-T"
   "MONOME-EVENT-CALLBACK-T"

   "MONOME-SET-ROTATION"
   "MONOME-GET-ROTATION"
   "MONOME-GET-SERIAL"
   "MONOME-GET-DEVPATH"
   "MONOME-GET-FRIENDLY-NAME"
   "MONOME-GET-PROTO"
   "MONOME-GET-ROWS"
   "MONOME-GET-COLS"

   "MONOME-LED-SET"
   "MONOME-LED-ON"
   "MONOME-LED-OFF"
   "MONOME-LED-ALL"
   "MONOME-LED-MAP"
   "MONOME-LED-COL"
   "MONOME-LED-ROW"
   "MONOME-LED-INTENSITY"
   "MONOME-LED-LEVEL-SET"
   "MONOME-LED-LEVEL-ALL"
   "MONOME-LED-LEVEL-MAP"
   "MONOME-LED-LEVEL-ROW"
   "MONOME-LED-LEVEL-COL"

   "MONOME-EVENT-GET-GRID"

   "MONOME-LED-RING-SET"
   "MONOME-LED-RING-ALL"
   "MONOME-LED-RING-MAP"
   "MONOME-LED-RING-RANGE"

   "MONOME-TILT-ENABLE"
   "MONOME-TILT-DISABLE"
   ))
