[
{ "tag": "typedef", "ns": 0, "name": "int_least8_t", "location": "/usr/include/stdint.h:43:22", "type": { "tag": ":signed-char", "bit-size": 8, "bit-alignment": 8 } },
{ "tag": "typedef", "ns": 0, "name": "int_least16_t", "location": "/usr/include/stdint.h:44:20", "type": { "tag": ":short", "bit-size": 16, "bit-alignment": 16 } },
{ "tag": "typedef", "ns": 0, "name": "int_least32_t", "location": "/usr/include/stdint.h:45:15", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "int_least64_t", "location": "/usr/include/stdint.h:50:24", "type": { "tag": ":long-long", "bit-size": 64, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "uint_least8_t", "location": "/usr/include/stdint.h:54:24", "type": { "tag": ":unsigned-char", "bit-size": 8, "bit-alignment": 8 } },
{ "tag": "typedef", "ns": 0, "name": "uint_least16_t", "location": "/usr/include/stdint.h:55:28", "type": { "tag": ":unsigned-short", "bit-size": 16, "bit-alignment": 16 } },
{ "tag": "typedef", "ns": 0, "name": "uint_least32_t", "location": "/usr/include/stdint.h:56:23", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "uint_least64_t", "location": "/usr/include/stdint.h:61:32", "type": { "tag": ":unsigned-long-long", "bit-size": 64, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "int_fast8_t", "location": "/usr/include/stdint.h:68:22", "type": { "tag": ":signed-char", "bit-size": 8, "bit-alignment": 8 } },
{ "tag": "typedef", "ns": 0, "name": "int_fast16_t", "location": "/usr/include/stdint.h:74:15", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "int_fast32_t", "location": "/usr/include/stdint.h:75:15", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "int_fast64_t", "location": "/usr/include/stdint.h:77:24", "type": { "tag": ":long-long", "bit-size": 64, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast8_t", "location": "/usr/include/stdint.h:81:24", "type": { "tag": ":unsigned-char", "bit-size": 8, "bit-alignment": 8 } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast16_t", "location": "/usr/include/stdint.h:87:23", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast32_t", "location": "/usr/include/stdint.h:88:23", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast64_t", "location": "/usr/include/stdint.h:90:32", "type": { "tag": ":unsigned-long-long", "bit-size": 64, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "intptr_t", "location": "/usr/include/stdint.h:103:15", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "uintptr_t", "location": "/usr/include/stdint.h:106:23", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "enum", "ns": 0, "name": "", "id": 1, "location": "/home/greg/proj/norns/matron/src/device/device_common.h:3:9", "fields": [{ "tag": "field", "name": "DEV_TYPE_MONOME", "value": 0 }, { "tag": "field", "name": "DEV_TYPE_HID", "value": 1 }, { "tag": "field", "name": "DEV_TYPE_MIDI", "value": 2 }, { "tag": "field", "name": "DEV_TYPE_COUNT", "value": 3 }, { "tag": "field", "name": "DEV_TYPE_INVALID", "value": 4 }] },
{ "tag": "typedef", "ns": 0, "name": "device_t", "location": "/home/greg/proj/norns/matron/src/device/device_common.h:13:3", "type": { "tag": ":enum", "name": "", "id": 1 } },
{ "tag": "function", "name": "dev_hid_init", "ns": 0, "location": "/home/greg/proj/norns/matron/src/device/device_hid.h:29:12", "variadic": false, "inline": false, "storage-class": "extern", "parameters": [{ "tag": "parameter", "name": "self", "type": { "tag": ":pointer", "type": { "tag": ":void" } } }, { "tag": "parameter", "name": "print", "type": { "tag": ":_Bool", "bit-size": 8, "bit-alignment": 8 } }], "return-type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "function", "name": "dev_hid_start", "ns": 0, "location": "/home/greg/proj/norns/matron/src/device/device_hid.h:30:14", "variadic": false, "inline": false, "storage-class": "extern", "parameters": [{ "tag": "parameter", "name": "self", "type": { "tag": ":pointer", "type": { "tag": ":void" } } }], "return-type": { "tag": ":pointer", "type": { "tag": ":void" } } },
{ "tag": "function", "name": "dev_hid_deinit", "ns": 0, "location": "/home/greg/proj/norns/matron/src/device/device_hid.h:31:13", "variadic": false, "inline": false, "storage-class": "extern", "parameters": [{ "tag": "parameter", "name": "self", "type": { "tag": ":pointer", "type": { "tag": ":void" } } }], "return-type": { "tag": ":void" } },
{ "tag": "const", "name": "bool", "ns": 0, "location": "/usr/lib/clang/5.0.1/include/stdbool.h:31:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__intptr_t_defined", "ns": 0, "location": "/usr/include/stdint.h:104:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "INT16_MAX", "ns": 0, "location": "/usr/include/stdint.h:132:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 32767 },
{ "tag": "const", "name": "INT8_MAX", "ns": 0, "location": "/usr/include/stdint.h:131:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 127 },
{ "tag": "const", "name": "INT64_MIN", "ns": 0, "location": "/usr/include/stdint.h:129:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "INT32_MIN", "ns": 0, "location": "/usr/include/stdint.h:128:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -2147483648 },
{ "tag": "const", "name": "INT16_MIN", "ns": 0, "location": "/usr/include/stdint.h:127:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -32768 },
{ "tag": "const", "name": "INT8_MIN", "ns": 0, "location": "/usr/include/stdint.h:126:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -128 },
{ "tag": "const", "name": "WINT_MAX", "ns": 0, "location": "/usr/include/stdint.h:255:10", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "WCHAR_MAX", "ns": 0, "location": "/usr/include/stdint.h:250:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "WINT_MIN", "ns": 0, "location": "/usr/include/stdint.h:254:10", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "false", "ns": 0, "location": "/usr/lib/clang/5.0.1/include/stdbool.h:33:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "true", "ns": 0, "location": "/usr/lib/clang/5.0.1/include/stdbool.h:32:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__bool_true_false_are_defined", "ns": 0, "location": "/usr/lib/clang/5.0.1/include/stdbool.h:42:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "PTRDIFF_MIN", "ns": 0, "location": "/usr/include/stdint.h:226:12", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -2147483648 },
{ "tag": "const", "name": "SIG_ATOMIC_MIN", "ns": 0, "location": "/usr/include/stdint.h:232:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -2147483648 },
{ "tag": "const", "name": "PTRDIFF_MAX", "ns": 0, "location": "/usr/include/stdint.h:227:12", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2147483647 },
{ "tag": "const", "name": "SIZE_MAX", "ns": 0, "location": "/usr/include/stdint.h:242:12", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "SIG_ATOMIC_MAX", "ns": 0, "location": "/usr/include/stdint.h:233:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2147483647 },
{ "tag": "const", "name": "WCHAR_MIN", "ns": 0, "location": "/usr/include/stdint.h:249:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__STDBOOL_H", "ns": 0, "location": "/usr/lib/clang/5.0.1/include/stdbool.h:27:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "INT_LEAST64_MIN", "ns": 0, "location": "/usr/include/stdint.h:147:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "INT_LEAST8_MAX", "ns": 0, "location": "/usr/include/stdint.h:149:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 127 },
{ "tag": "const", "name": "INT_LEAST32_MAX", "ns": 0, "location": "/usr/include/stdint.h:151:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2147483647 },
{ "tag": "const", "name": "INT_LEAST16_MAX", "ns": 0, "location": "/usr/include/stdint.h:150:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 32767 },
{ "tag": "const", "name": "INT_LEAST64_MAX", "ns": 0, "location": "/usr/include/stdint.h:152:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "UINT_LEAST8_MAX", "ns": 0, "location": "/usr/include/stdint.h:155:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 255 },
{ "tag": "const", "name": "UINT_LEAST16_MAX", "ns": 0, "location": "/usr/include/stdint.h:156:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 65535 },
{ "tag": "const", "name": "UINT_LEAST64_MAX", "ns": 0, "location": "/usr/include/stdint.h:158:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "INT32_MAX", "ns": 0, "location": "/usr/include/stdint.h:133:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2147483647 },
{ "tag": "const", "name": "INT64_MAX", "ns": 0, "location": "/usr/include/stdint.h:134:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "UINT8_MAX", "ns": 0, "location": "/usr/include/stdint.h:137:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 255 },
{ "tag": "const", "name": "UINT_LEAST32_MAX", "ns": 0, "location": "/usr/include/stdint.h:157:10", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "UINT16_MAX", "ns": 0, "location": "/usr/include/stdint.h:138:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 65535 },
{ "tag": "const", "name": "UINT32_MAX", "ns": 0, "location": "/usr/include/stdint.h:139:10", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "UINT64_MAX", "ns": 0, "location": "/usr/include/stdint.h:140:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "INT_LEAST8_MIN", "ns": 0, "location": "/usr/include/stdint.h:144:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -128 },
{ "tag": "const", "name": "INT_LEAST16_MIN", "ns": 0, "location": "/usr/include/stdint.h:145:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -32768 },
{ "tag": "const", "name": "INT_LEAST32_MIN", "ns": 0, "location": "/usr/include/stdint.h:146:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -2147483648 },
{ "tag": "const", "name": "UINT_FAST16_MAX", "ns": 0, "location": "/usr/include/stdint.h:188:11", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "UINT_FAST32_MAX", "ns": 0, "location": "/usr/include/stdint.h:189:11", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "UINT_FAST64_MAX", "ns": 0, "location": "/usr/include/stdint.h:191:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "UINTPTR_MAX", "ns": 0, "location": "/usr/include/stdint.h:202:11", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "INTPTR_MIN", "ns": 0, "location": "/usr/include/stdint.h:200:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -2147483648 },
{ "tag": "const", "name": "INTMAX_MIN", "ns": 0, "location": "/usr/include/stdint.h:207:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "INTPTR_MAX", "ns": 0, "location": "/usr/include/stdint.h:201:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2147483647 },
{ "tag": "const", "name": "INTMAX_MAX", "ns": 0, "location": "/usr/include/stdint.h:209:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "UINTMAX_MAX", "ns": 0, "location": "/usr/include/stdint.h:212:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "INT_FAST8_MIN", "ns": 0, "location": "/usr/include/stdint.h:162:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -128 },
{ "tag": "const", "name": "INT_FAST32_MIN", "ns": 0, "location": "/usr/include/stdint.h:168:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -2147483648 },
{ "tag": "const", "name": "INT_FAST16_MIN", "ns": 0, "location": "/usr/include/stdint.h:167:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -2147483648 },
{ "tag": "const", "name": "INT_FAST32_MAX", "ns": 0, "location": "/usr/include/stdint.h:178:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2147483647 },
{ "tag": "const", "name": "INT_FAST64_MIN", "ns": 0, "location": "/usr/include/stdint.h:170:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "INT_FAST64_MAX", "ns": 0, "location": "/usr/include/stdint.h:180:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "INT_FAST8_MAX", "ns": 0, "location": "/usr/include/stdint.h:172:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 127 },
{ "tag": "const", "name": "UINT_FAST8_MAX", "ns": 0, "location": "/usr/include/stdint.h:183:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 255 },
{ "tag": "const", "name": "INT_FAST16_MAX", "ns": 0, "location": "/usr/include/stdint.h:177:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2147483647 },
{ "tag": "const", "name": "__GLIBC_INTERNAL_STARTING_HEADER_IMPLEMENTATION", "ns": 0, "location": "/usr/include/stdint.h:25:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "_STDINT_H", "ns": 0, "location": "/usr/include/stdint.h:23:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 }
]
