(defpackage :matron
  (:use :common-lisp :cffi)

  (:export
   "GPIO-INIT"
   "GPIO-DEINIT"

   "I2C-INIT"
   "I2C-DEINIT"
   "I2C-HP"

   "BATTERY-INIT"
   "BATTERY-DEINIT"

   ;; screen functions
   "SCREEN-INIT"
   "SCREEN-DEINIT"
   "SCREEN-UPDATE"
   "SCREEN-SAVE"
   "SCREEN-RESTORE"
   "SCREEN-FONT-FACE"
   "SCREEN-FONT-SIZE"
   "SCREEN-AA"
   "SCREEN-LEVEL"
   "SCREEN-LINE"
   "SCREEN-LINE-REL"
   "SCREEN-LINE-WIDTH"
   "SCREEN-LINE-CAP"
   "SCREEN-LINE-JOIN"
   "SCREEN-MITER-LIMIT"
   "SCREEN-MOVE"
   "SCREEN-MOVE-REL"
   "SCREEN-CURVE"
   "SCREEN-CURVE-REL"
   "SCREEN-CURVE"
   "SCREEN-ARC"
   "SCREEN-RECT"
   "SCREEN-STROKE"
   "SCREEN-FILL"
   "SCREEN-TEXT"
   "SCREEN-CLEAR"
   "SCREEN-CLOSE-PATH"
   "SCREEN-EXTENTS"

   ;; screen helpers
   "SCREEN-TEXT-CENTER"
   "SCREEN-TEXT-RIGHT"
   "SCREEN-CIRCLE"

   ;; screen cap/miter constants
   "+CAP-BUTT+"
   "+CAP-ROUND+"
   "+CAP-SQUARE+"
   "+JOIN-MITER+"
   "+JOIN-ROUND+"
   "+JOIN-BEVEL+"

   ;; events and types
   "SIZE-T"
   "EVENT-HANDLER-T"
   "FREE-EVENT-DATA-T"
   "POLL-TYPE-T"
   "ENGINE-COMMAND-T"
   "ENGINE-POLL-T"
   "ENGINE-PARAM-T"
   "OSC-MESSAGE-T"
   "EVENT-T"
   "QUAD-LEVELS-T"
   "EVENT-COMMON-T"
   "EVENT-EXEC-CODE-LINE-T"
   "EVENT-MONOME-ADD-T"
   "EVENT-MONOME-REMOVE-T"
   "EVENT-GRID-KEY-T"
   "EVENT-ARC-ENCODER-DELTA-T"
   "EVENT-ARC-ENCODER-KEY-T"
   "EVENT-HID-ADD-T"
   "EVENT-HID-REMOVE-T"
   "EVENT-HID-EVENT-T"
   "EVENT-MIDI-ADD-T"
   "EVENT-MIDI-REMOVE-T"
   "EVENT-MIDI-EVENT-T"
   "EVENT-OSC-T"
   "EVENT-METRO-T"
   "EVENT-KEY-T"
   "EVENT-BATTERY-T"
   "EVENT-POWER-T"
   "EVENT-STAT-T"
   "EVENT-ENC-T"
   "EVENT-POLL-VALUE-T"
   "EVENT-POLL-IO-LEVELS-T"
   "EVENT-POLL-DATA-T"
   "EVENT-POLL-WAVE-T"
   "EVENT-STARTUP-READY-OK-T"
   "EVENT-STARTUP-READY-TIMEOUT-T"
   "EVENT-DATA-T"
   "EVENT-DATA-PTR-T"

   ;; event globals, constants
   "*EVENT-LOOP-QUIT*"
   "+EVENT-WAVE-DISPLAY-BYTES+"

   ;; event functions
   "EVENTS-INIT"
   "EVENT-SET-HANDLER"
   "EVENT-LOOP"
   "EVENT-DATA-NEW"
   "EVENT-DATA-FREE"
   "EVENT-POST"

   ;; metro functions
   "METROS-INIT"
   "METRO-START"
   "METRO-STOP"
   "METRO-SET-TIME"

   ;; device
   "SSIZE-T"
   "DEVICE-T"
   "DEV-START-T"
   "DEV-DEINIT-T"
   "DEV-COMMON-T"
   "DEVICE-MONOME-TYPE-T"
   "MONOME-T"

   "+MONOME-BUFFER-SIZE+"

   "DEV-MONOME-T"
   "DEV-MONOME-PTR-T"

   "DEV-MONOME-GRID-SET-LED"
   "DEV-MONOME-ARC-SET-LED"
   "DEV-MONOME-ALL-LED"
   "DEV-MONOME-SET-QUAD"
   "DEV-MONOME-REFRESH"
   "DEV-MONOME-GRID-ROWS"
   "DEV-MONOME-GRID-COLS"
   "DEV-MONOME-SET-ROTATION"

   "%MONOME-SELF-PTR-T"

   "DEV-MONOME-INIT"
   "DEV-MONOME-DEINIT"
   "DEV-MONOME-START"

   "DEV-VID-T"
   "DEV-PID-T"
   "DEV-CODE-T"

   "DEV-HID-T"
   "%HID-SELF-PTR-T"

   "DEV-HID-INIT"
   "DEV-HID-DEINIT"
   "DEV-HID-START"

   "DEV-MIDI-T"
   "%MIDI-SELF-PTR-T"

   "DEV-MIDI-INIT"
   "DEV-MIDI-DEINIT"
   "DEV-MIDI-START"
   "DEV-MIDI-SEND"

   "DEV-T"
   "DEV-PTR-T"

   "DEVICES-INIT"
   "DEV-NEW"
   "DEV-DELETE"
   "DEV-ID"
   "DEV-SERIAL"
   "DEV-NAME"

   "DEV-LIST-INIT"
   "DEV-LIST-ADD"
   "DEV-LIST-REMOVE"

   "DEV-MONITOR-INIT"
   "DEV-MONITOR-DEINIT"
   "DEV-MONITOR-SCAN"

   ))
